package com.bird.search.dto;

import lombok.Getter;
import lombok.Setter;

/**
 * Data Transfer Object for attribute generation responses.
 *
 * <p>Contains the complete metadata structure generated by the AI model
 * based on the user's partial description.</p>
 */
@Getter
@Setter
public class AttributeGenerationResponse {

  /** Generated metadata containing attribute details. */
  private Metadata metadata;

}
